### ISSUE TITLE
toast-notifications inside modal.

### ISSUE THREAD

**Issue by franciscoSankhya** [arnnis/react-native-toast-notifications#102] opened 2021-10-01 14:55 UTC
### Current behaviour

toastWarnings doesnt work inside Modal

### Expected behaviour

expected to work inside modal, not in parent component

### Code sample

running app via USB

**Comment by arnnis** [comment] 2021-10-03 07:14
This is a duplicate of #50 and #85. The following FAQ may help [How to show toast inside a Modal?](https://github.com/arnnis/react-native-toast-notifications#--how-to-show-toast-inside-a-modal)

**Closed by arnnis** 2021-10-03 07:14 UTC
Labels: bug

**Comment by carrie503** [comment] 2023-07-17 09:43
I have written another workaroud so we can use `useToast`

See here:
https://github.com/arnnis/react-native-toast-notifications/issues/50#issuecomment-1637708341
